language: java
jdk: oraclejdk8

branches:
  only:
  - master

git:
  depth: 99999

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5


jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn sonar:sonar


addons:
  sonarcloud:
    organization: "symonk-github"
    token:
      secure: ${SLACK_TOKEN}
