language: java
jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn verify -Dselenide.browser=chrome -Dthread.count=10 -Dexplicit.wait.timeout=15000

branches:
  only:
  - master

git:
  depth: 99999