language: java
jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn sonar:sonar
    script: sbt clean coverage test


branches:
  only:
  - master

addons:
  apt:
    update: true
   sonarcloud:
      organization: "symonk-github"
  chrome: stable

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

before_cache:
  - rm -fr /home/travis/.m2/repository/webdriver/

after_success: "sbt coveralls"


git:
  depth: 99999