language: java
jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn verify -Dselenide.browser=chrome -Dthread.count=10 -Dexplicit.wait.timeout=15000

branches:
  only:
  - master

addons:
  apt:
    update: true
  chrome: stable

before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - export CHROME_BIN=/usr/bin/google-chrome

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5


git:
  depth: 99999