language: java
jdk: oraclejdk8
branches:
  only:
  - master
git:
  depth: 99999
before_install:
- sudo apt-get install -y libappindicator1 fonts-liberation
- export CHROME_BIN=/usr/bin/google-chrome
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: symonk-github
    token:
      secure: "PsElkkrqWTO4CqQ04szmc8mj2wZYXan9dFsQngaAXlsviIBhfUDI8cyMDge0DNDhDR3XFwiu/MvPOicjGpfXQshqKn7Rbhb4VSek79SZZAEBjCnzNmAo8lbhPCtHuRVuqrx5t/DpEbT6WaPLKxRhkGvopkrL9oGgzwH39+7B2Vqys0YocJSDt5sbjveAJlNdPEvmhV1Fh9gNKIJc3zkmFgWxWltHh3CFthvS5MPeo6Zwsv4ngSKGjk6pagd6G96f1sOtfmVQkrQ3S2sbiZmKkFBIpCvk9DmmR8YHhcJcNbpLfUya6oYGSlrGsH1NkhGPBGj++/dCvmHuo0H+gmxzRG23kZme8Mu8nOJ8dRucp0ezmfSjc/MpFC3KnI/L1QS3OZJfx5xUBVhnMdVVPxZYgmtxLgTMtVYsAbrjdvHp1q8vROxdKcVN8B5FjJSxOf7cwSUWuMXS9FyGI1ZO+155xoftKBMgEk65ZZKjT2KxwwbHfmhvINbLCf9KKLBmTjHaE9XXDExKSSVd7pzEUrWOeg8EtqtjUekWOms0TirOc0kgooXHmzTMl3tkHpA3p/Lb/JmD5bFwAFUFRjL7/qiRfpAWRRFcGMH5XpO7SeFaQHR4OMlkdcznUi/ADdyoRr+wl5Rx1gzB0NcCSQa1ZXoEq7/JyaZokKLcU/xvhwzNkoA="
